consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: gliderlabs/consul-server:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "172.17.0.1:53:8600/udp"

registrator:
  command: -ip 172.17.0.1 consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
    - consul
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

geoserver:
  image: kartoza/geoserver:2.8.0
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  ports:
    - "8080:8080"
  links:
    - postgres
  environment:
    SERVICE_NAME: geoserver
    SERVICE_TAGS: geo,wms,wfs
    SERVICE_CHECK_HTTP: /
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s

postgres:
  image: kartoza/postgis:9.4-2.1
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  ports:
    - "5432:5432"
  environment:
    SERVICE_NAME: postgres
    SERVICE_TAGS: db,gis,postgis
    SERVICE_CHECK_TCP: true
    SERVICE_CHECK_INTERVAL: 15s
    SERVICE_CHECK_TIMEOUT: 1s
